import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams, useNavigate } from "react-router-dom";
import { api } from "../lib/api";
import { PageHeader } from "../components/AppShell";
import { useCurrentUser, can } from "../hooks/useAuth";
import { pillClassFor, fmtMoney, fmtDate } from "../lib/financial";

interface Row {
  id: number; claimNumber: string; partnerId: number; partnerName: string | null;
  status: string; totalAmount: string; autoGenerated: boolean;
  submittedAt: string | null; approvedAt: string | null; rejectedAt: string | null; settledAt: string | null;
  createdAt: string;
}

export function ClaimsPage() {
  const { t } = useTranslation();
  const [status, setStatus] = useState("");
  const list = useQuery({
    queryKey: ["claims", status],
    queryFn: () => api<Row[]>(`/api/claims?${new URLSearchParams({ status }).toString()}`),
  });

  return (
    <div>
      <PageHeader title={t("nav.claims")} subtitle={t("claims.subtitle")} />
      <div className="mb-4">
        <select className="input" value={status} onChange={(e) => setStatus(e.target.value)}>
          <option value="">{t("common.all")}</option>
          {["draft","approved","rejected","settled"].map((s) => <option key={s} value={s}>{t(`financial.claimStatuses.${s}`)}</option>)}
        </select>
      </div>
      <div className="table-wrap">
        <table className="table">
          <thead>
            <tr>
              <th>{t("claims.number")}</th>
              <th>{t("common.partner")}</th>
              <th className="text-end">{t("partnerCommissions.amount")}</th>
              <th>{t("common.status")}</th>
              <th>{t("claims.autoGenerated")}</th>
              <th>{t("claims.submittedAt")}</th>
              <th>{t("common.actions")}</th>
            </tr>
          </thead>
          <tbody>
            {list.isLoading && <tr><td colSpan={7} className="text-center py-8 text-muted">{t("common.loading")}</td></tr>}
            {list.data?.length === 0 && <tr><td colSpan={7} className="text-center py-8 text-muted">{t("common.noData")}</td></tr>}
            {list.data?.map((r) => (
              <tr key={r.id}>
                <td className="font-mono text-xs"><Link to={`/claims/${r.id}`} className="text-violet-700 hover:underline">{r.claimNumber}</Link></td>
                <td>{r.partnerName}</td>
                <td className="text-end font-mono font-semibold">{fmtMoney(r.totalAmount)}</td>
                <td><span className={pillClassFor(r.status)}>{t(`financial.claimStatuses.${r.status}`)}</span></td>
                <td>{r.autoGenerated ? <span className="pill-violet">{t("common.auto")}</span> : <span className="pill-muted">{t("common.manual")}</span>}</td>
                <td className="text-xs text-muted">{fmtDate(r.submittedAt)}</td>
                <td><Link to={`/claims/${r.id}`} className="text-violet-700 text-sm hover:underline">{t("common.view")}</Link></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

interface ClaimDetail {
  claim: {
    id: number; claimNumber: string; partnerId: number; status: string;
    totalAmount: string; autoGenerated: boolean; notes: string | null;
    submittedAt: string | null; approvedAt: string | null; rejectedAt: string | null;
    rejectionReason: string | null; settledAt: string | null;
  };
  items: Array<{ id: number; partnerCommissionId: number; amount: string; customerName: string | null; packageName: string | null }>;
  approverName: string | null;
}

export function ClaimDetailPage() {
  const { id } = useParams();
  const { t } = useTranslation();
  const { data: user } = useCurrentUser();
  const qc = useQueryClient();
  const nav = useNavigate();
  const detail = useQuery({
    queryKey: ["claim", id],
    queryFn: () => api<ClaimDetail>(`/api/claims/${id}`),
    enabled: !!id,
  });
  const approve = useMutation({
    mutationFn: () => api(`/api/claims/${id}/approve`, { method: "POST" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["claim", id] }),
  });
  const reject = useMutation({
    mutationFn: (reason: string) => api(`/api/claims/${id}/reject`, { method: "POST", json: { reason } }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["claim", id] }),
  });
  if (detail.isLoading || !detail.data) return <div className="text-center text-muted py-12">{t("common.loading")}</div>;
  const { claim, items } = detail.data;
  const isCompanyAcct = user?.roleKey === "company_super_admin" || user?.roleKey === "company_accountant";

  return (
    <div>
      <PageHeader
        title={`${t("claims.number")} ${claim.claimNumber}`}
        subtitle={`${t("common.partner")} #${claim.partnerId}`}
        actions={
          isCompanyAcct && claim.status === "draft" ? (
            <div className="flex gap-2">
              <button className="btn-primary" onClick={() => approve.mutate()}>{t("claims.approve")}</button>
              <button className="btn-ghost text-red-700" onClick={() => {
                const r = prompt(t("requests.reason") as string);
                if (r) reject.mutate(r);
              }}>{t("claims.reject")}</button>
            </div>
          ) : null
        }
      />
      <div className="grid md:grid-cols-3 gap-4 mb-4">
        <div className="stamp-card p-5">
          <div className="text-xs text-muted">{t("common.status")}</div>
          <div className="mt-2"><span className={pillClassFor(claim.status)}>{t(`financial.claimStatuses.${claim.status}`)}</span></div>
        </div>
        <div className="stamp-card p-5">
          <div className="text-xs text-muted">{t("partnerCommissions.amount")}</div>
          <div className="text-2xl font-bold text-violet-700 mt-1">{fmtMoney(claim.totalAmount)}</div>
        </div>
        <div className="stamp-card p-5">
          <div className="text-xs text-muted">{t("claims.itemCount")}</div>
          <div className="text-2xl font-bold mt-1">{items.length}</div>
        </div>
      </div>
      <div className="table-wrap">
        <table className="table">
          <thead><tr><th>{t("common.customer")}</th><th>{t("packages.title")}</th><th className="text-end">{t("partnerCommissions.amount")}</th></tr></thead>
          <tbody>
            {items.map((i) => (
              <tr key={i.id}>
                <td>{i.customerName}</td>
                <td>{i.packageName}</td>
                <td className="text-end font-mono">{fmtMoney(i.amount)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {claim.rejectionReason && (
        <div className="mt-4 stamp-card p-4 border-red-200 bg-red-50/50">
          <div className="text-xs text-red-700 font-semibold mb-1">{t("requests.rejectionReason")}</div>
          <div className="text-sm">{claim.rejectionReason}</div>
        </div>
      )}
    </div>
  );
}
