import { Router } from "express";
import { and, desc, eq, sql } from "drizzle-orm";
import { z } from "zod";
import { db } from "../db.js";
import {
  claims, claimItems, partnerCommissions, partners, customers, packages, users,
} from "../schema.js";
import { getUser, requirePerm } from "../auth.js";
import { createClaim, approveClaim, rejectClaim } from "../financial.js";

export const claimsRouter = Router();

function partnerScoped(cu: { roleKey: string; partnerId: number | null }) {
  return cu.partnerId && cu.roleKey !== "company_super_admin" && cu.roleKey !== "company_accountant";
}

claimsRouter.get("/", requirePerm("claims:view"), async (req, res) => {
  const cu = getUser(req)!;
  const { status, partnerId, from, to } = req.query as Record<string, string | undefined>;
  const filters: any[] = [];
  if (partnerScoped(cu)) filters.push(eq(claims.partnerId, cu.partnerId!));
  else if (partnerId) filters.push(eq(claims.partnerId, Number(partnerId)));
  if (status) filters.push(eq(claims.status, status));
  if (from) filters.push(sql`${claims.createdAt} >= ${new Date(from)}`);
  if (to) filters.push(sql`${claims.createdAt} <= ${new Date(to)}`);
  const where = filters.length ? and(...filters) : undefined;
  const q = db
    .select({
      id: claims.id,
      claimNumber: claims.claimNumber,
      partnerId: claims.partnerId,
      partnerName: partners.name,
      status: claims.status,
      totalAmount: claims.totalAmount,
      autoGenerated: claims.autoGenerated,
      submittedAt: claims.submittedAt,
      approvedAt: claims.approvedAt,
      rejectedAt: claims.rejectedAt,
      settledAt: claims.settledAt,
      createdAt: claims.createdAt,
    })
    .from(claims)
    .leftJoin(partners, eq(partners.id, claims.partnerId));
  const rows = where ? await q.where(where).orderBy(desc(claims.createdAt)).limit(200) : await q.orderBy(desc(claims.createdAt)).limit(200);
  res.json(rows);
});

claimsRouter.get("/eligible", requirePerm("claims:view"), async (req, res) => {
  const cu = getUser(req)!;
  const partnerId = partnerScoped(cu) ? cu.partnerId! : Number(req.query.partnerId);
  if (!partnerId) return res.status(400).json({ error: "partner_required" });
  const rows = await db
    .select({
      id: partnerCommissions.id,
      customerName: customers.name,
      packageName: packages.name,
      amount: partnerCommissions.amount,
      pct: partnerCommissions.pct,
      baseAmount: partnerCommissions.baseAmount,
      createdAt: partnerCommissions.createdAt,
    })
    .from(partnerCommissions)
    .leftJoin(customers, eq(customers.id, partnerCommissions.customerId))
    .leftJoin(packages, eq(packages.id, partnerCommissions.packageId))
    .where(and(eq(partnerCommissions.partnerId, partnerId), eq(partnerCommissions.status, "eligible_for_claim")))
    .orderBy(desc(partnerCommissions.createdAt));
  res.json(rows);
});

claimsRouter.get("/:id", requirePerm("claims:view"), async (req, res) => {
  const id = Number(req.params.id);
  const cu = getUser(req)!;
  const [c] = await db.select().from(claims).where(eq(claims.id, id));
  if (!c) return res.status(404).json({ error: "not_found" });
  if (partnerScoped(cu) && c.partnerId !== cu.partnerId) return res.status(403).json({ error: "forbidden" });
  const items = await db
    .select({
      id: claimItems.id,
      partnerCommissionId: claimItems.partnerCommissionId,
      amount: claimItems.amount,
      customerName: customers.name,
      packageName: packages.name,
    })
    .from(claimItems)
    .leftJoin(partnerCommissions, eq(partnerCommissions.id, claimItems.partnerCommissionId))
    .leftJoin(customers, eq(customers.id, partnerCommissions.customerId))
    .leftJoin(packages, eq(packages.id, partnerCommissions.packageId))
    .where(eq(claimItems.claimId, id));
  const [approver] = c.approvedByUserId
    ? await db.select({ name: users.name }).from(users).where(eq(users.id, c.approvedByUserId))
    : [{ name: null }];
  res.json({ claim: c, items, approverName: approver?.name ?? null });
});

const createInput = z.object({
  partnerId: z.coerce.number().int().optional(),
  partnerCommissionIds: z.array(z.coerce.number().int()).min(1),
  notes: z.string().optional(),
});

claimsRouter.post("/", requirePerm("claims:create"), async (req, res) => {
  const cu = getUser(req)!;
  const parsed = createInput.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: "invalid_input", details: parsed.error.flatten() });
  const partnerId = partnerScoped(cu) ? cu.partnerId! : (parsed.data.partnerId ?? cu.partnerId ?? 0);
  if (!partnerId) return res.status(400).json({ error: "partner_required" });
  try {
    const result = await createClaim({
      partnerId,
      partnerCommissionIds: parsed.data.partnerCommissionIds,
      userId: cu.id,
      notes: parsed.data.notes,
    });
    res.json(result);
  } catch (e: any) {
    res.status(400).json({ error: e.message ?? "failed" });
  }
});

claimsRouter.post("/:id/approve", requirePerm("claims:approve"), async (req, res) => {
  const cu = getUser(req)!;
  if (cu.roleKey !== "company_super_admin" && cu.roleKey !== "company_accountant") return res.status(403).json({ error: "forbidden" });
  try {
    await approveClaim(Number(req.params.id), cu.id);
    res.json({ ok: true });
  } catch (e: any) {
    res.status(409).json({ error: e.message });
  }
});

const rejectInput = z.object({ reason: z.string().min(2) });
claimsRouter.post("/:id/reject", requirePerm("claims:reject"), async (req, res) => {
  const cu = getUser(req)!;
  if (cu.roleKey !== "company_super_admin" && cu.roleKey !== "company_accountant") return res.status(403).json({ error: "forbidden" });
  const parsed = rejectInput.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: "invalid_input" });
  try {
    await rejectClaim(Number(req.params.id), cu.id, parsed.data.reason);
    res.json({ ok: true });
  } catch (e: any) {
    res.status(409).json({ error: e.message });
  }
});
